import time
def faizmenü():    
    print("╔═════════════════════╗")
    print("║    Faizler          ║")
    print("║                     ║")
    print("║  1-Yıllık           ║")
    print("║  2-Aylık            ║")
    print("║  3-Günlük           ║")
    print("║  4-Ana Menü         ║")
    print("║                     ║")
    print("║                     ║")
    print("║    Seçimiz nedir?   ║")
    print("╚═════════════════════╝")
    print()
    secim=input("Yapmak istediğiniz işlemin başındaki sayıyı yazınız:")
